<?php

	require_once "main.php";

	#Conexion a la db#
	$infoDog = conexion();
	$infoDog = $infoDog -> query(SELECT * FROM asoprofasil);

	if($infoDog->rowCount()>=1) {
		$infoDog = $infoDog->fetchAll();
	}

	echo '
		<article class="article_dog">This is a DIV generated by PHP.</article>
	';