<?php
// prueba de div
echo '
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
	<article class="article_dog">This is a DIV generated by PHP.</article>
';

